const citiesAndDistricts = {
    İstanbul: ["Kadıköy", "Beşiktaş", "Üsküdar", "Fatih", "Şişli"],
    Ankara: ["Çankaya", "Keçiören", "Yenimahalle", "Sincan", "Etimesgut"],
    İzmir: ["Konak", "Karşıyaka", "Bornova", "Buca", "Bayraklı"],
    Antalya: ["Muratpaşa", "Kepez", "Alanya", "Manavgat", "Kemer"],
    Bursa: ["Osmangazi", "Nilüfer", "Yıldırım", "İnegöl", "Gemlik"],
    Edirne: ["Merkez", "Erikli", "İpsala", "Enez", "Havsa", "Keşan", "Lalapaşa", "Uzunköprü"],
    Tekirdağ: ["Süleymanpaşa", "Çorlu", "Kapaklı", "Saray", "Çerkezköy"],
    Adana: ["Seyhan", "Yüreğir", "Çukurova", "Karaisalı", "Aladağ"],
    Erzurum: ["Yakutiye", "Palandöken", "Aziziye", "Köprüköy", "Çat"],
    Mersin: ["Akdeniz", "Toroslar", "Mezitli", "Erdemli", "Silifke"],
    Gaziantep: ["Şahinbey", "Şehitkamil", "Oğuzeli", "Karkamış", "Nizip"],
    Konya: ["Selçuklu", "Meram", "Karatay", "Akşehir", "Ilgın"],
    Kayseri: ["Kocasinan", "Melikgazi", "Develi", "Talas", "Hacılar"],
    Samsun: ["Atakum", "İlkadım", "Canik", "Tekkeköy", "Ladik"],
    Trabzon: ["Ortahisar", "Akçaabat", "Sürmene", "Vakfıkebir", "Arsin"],
    Balıkesir: ["Altıeylül", "Karesi", "Bandırma", "Edremit", "Gönen"],
    Manisa: ["Şehzadeler", "Yunusemre", "Salihli", "Akhisar", "Turgutlu"],
    Aydın: ["Efeler", "Söke", "Nazilli", "Kuşadası", "Bozdoğan"],
    Diyarbakır: ["Sur", "Bağlar", "Yenişehir", "Kayapınar", "Eğil"],
    Şanlıurfa: ["Haliliye", "Eyyübiye", "Karaköprü", "Siverek", "Viranşehir"],
    Kocaeli: ["İzmit", "Gebze", "Derince", "Kartepe", "Dilovası"],
    Şırnak: ["Merkez", "Silopi", "Cizre", "İdil", "Beytüşşebap"],
    Van: ["İpekyolu", "Edremit", "Tuşba", "Muradiye", "Erciş"],
    Rize: ["Merkez", "Ardeşen", "Çayeli", "Pazar", "Fındıklı"],
    Sakarya: ["Adapazarı", "Erenler", "Serdivan", "Hendek", "Akyazı"],
    Çorum: ["Merkez", "İskilip", "Alaca", "Sungurlu", "Osmancık"],
    Afyonkarahisar: ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "İhsaniye"],
    Bilecik: ["Merkez", "İnhisar", "Bozüyük", "Gölpazarı", "Pazaryeri"],
    Artvin: ["Merkez", "Hopa", "Borçka", "Ardanuç", "Murgul"],
    Aksaray: ["Merkez", "Sarıyahşi", "Ağaçören", "Kızılkaya", "Ortaköy"],
    Isparta: ["Merkez", "Göller", "Senirkent", "Yalvaç", "Keçiborlu"],
    Karabük: ["Merkez", "Safranbolu", "Eflani", "Ovacık", "Yenice"],
    Bartın: ["Merkez", "Amasra", "Kurucaşile", "Ulus", "İnkumu"],
    Çankırı: ["Merkez", "Ilgaz", "Korgun", "Atkaracalar", "Eldivan"],
    Kütahya: ["Merkez", "Tavşanlı", "Simav", "Gediz", "Domaniç"],
    Kırıkkale: ["Merkez", "Delice", "Balışeyh", "Keskin", "Sulakyurt"],
    Kilis: ["Merkez", "Polateli", "Elbeyli", "Musabeyli", "Türkeli"],
    Nevşehir: ["Merkez", "Avanos", "Derinkuyu", "Acıgöl", "Hacıbektaş"],
    Niğde: ["Merkez", "Bor", "Altunhisar", "Çamardı", "Ulukışla"],
    Osmaniye: ["Merkez", "Düziçi", "Toprakkale", "Bahçe", "Kadirli"],
    Zonguldak: ["Merkez", "Ereğli", "Alaplı", "Devrek", "Çaycuma"],
    Giresun: ["Merkez", "Eynesil", "Piraziz", "Şebinkarahisar", "Keşap"],
    Yozgat: ["Merkez", "Sorgun", "Akdağmadeni", "Çayıralan", "Sarıkaya"],
    Karaman: ["Merkez", "Ermenek", "Kazımkarabekir", "Ayrancı", "Başyayla"],
    Mardin: ["Merkez", "Kızıltepe", "Nusaybin", "Artuklu", "Midyat"],
    

  };
  export default citiesAndDistricts;